### ISSUE TITLE
Building Fails

### ISSUE THREAD

**Issue by boada** [dmulholland/ivy#1]
We'll start from the beginning... 

> $ pip3 install -U ivy --user
Collecting ivy
Requirement already up-to-date: jinja2<3.0,>=2.8 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: pyyaml<4.0,>=3.11 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: libclio<3.0.0,>=2.0.0 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: pygments<3.0.0,>=2.1.3 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: shortcodes<3.0.0,>=2.1.0 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: ibis<2.0.0,>=1.6.0 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: syntex in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: markdown<3.0.0,>=2.6.6 in ./.local/lib/python3.5/site-packages (from ivy)
Requirement already up-to-date: MarkupSafe>=0.23 in ./.local/lib/python3.5/site-packages (from jinja2<3.0,>=2.8->ivy)
Installing collected packages: ivy
Successfully installed ivy-0.4.6

So far so good.

> $ mkdir mysite
$ cd mysite
$ ivy init
$ ls
ext  inc  lib  out  res  site.py  src
$ ivy build
Traceback (most recent call last):
  File "./.local/bin/ivy", line 7, in <module>
    from ivy import main
ImportError: No module named 'ivy'

Ok. But if I change into a lower directory...

> $ cd res
$ ivy build
Rendered:     5  ·  Written:     5  ·  Time:  0.16 sec  ·  Avg: 0.0312 sec/page

What? -- This is almost certainly *not* a problem with `Ivy` but I figured I'd post it here in case anyone else gets a similar issue. I'm not sure what the problem is.  Interestingly, being the in `mysite` directory after I run `ivy init` it breaks all of my python..

> mysite$ ipython3
Traceback (most recent call last):
  File "./.local/bin/ipython3", line 7, in <module>
    from IPython import start_ipython
ImportError: No module named 'IPython'

Thoughts?

**Comment by dmulholland** [comment]
Thanks for reporting the issue - it's certainly a new one to me. Just to check out a hunch, what happens if you delete or rename the `site.py` file in the site's home directory?

**Comment by boada** [comment]
Works. 

> $ mv site.py site.py.bak
$ ivy build
Rendered:     5  ·  Written:     5  ·  Time:  0.16 sec  ·  Avg: 0.0325 sec/page

**Comment by dmulholland** [comment]
Ha, I had a vague memory of something like this biting me years ago!

I think Python is confusing the `site.py` file in the home directory for the `site` module in its standard library which has some role in initialising the interpreter. I'm not sure why though - I don't think Python is supposed to look in the current directory for imported libraries. Obviously it doesn't normally or this would be an issue all the time.

Any ideas why it would be happening in your case?

**Comment by boada** [comment]
Ok. 

Python searches `sys.path` in order for the modules you are trying to import. 

>$ ipython3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: TkAgg

>In [1]: import sys
In [2]: sys.path
Out[2]: 
['',
 '$HOME/.local/bin',
 '$HOME/mysite',
...]

I've clipped and edited the output. Because `site.py` is part of the standard library, it finds that file and then tries to use it when it is importing everything else. Breaking everything. Seems like the name should be changed to something other than `site.py`

**Comment by dmulholland** [comment]
I suspect this may be an IPython issue. If you look at how [sys.path](https://docs.python.org/3.6/library/sys.html#sys.path) is populated, the first item is normally the directory containing the invoking script. The current directory is only checked in interactive mode.

I wonder if IPython is hardwiring a check of the current directory on the assumption that all use is interactive use? If it is, that would seem open a security hole as running any Python application in a directory containing a malicious `site.py` file would automatically execute the script.

I could definitely change the name of the site configuration file to say `ivy.py`, but the deeper issue here is allowing an arbitrarily named file in the current directory to break the interpreter or compromise the system. I don't use IPython myself but it might be worth raising the issue with the developers if you do.

**Comment by boada** [comment]
I dunno. Here is it without using IPython, and just talking to the interpreter directly.

> $ cd mysite/
$ rm -r *
$ ivy init
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
$ import sys
$ print(sys.path)
['', '', '$HOME/.../...', '/usr/lib/python35.zip', '/usr/lib/python3.5/', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload']
$ import ivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ivy'

**Comment by dmulholland** [comment]
This is mostly the output I'd expect. If you run `print(sys.path)` in interactive mode the first element is `''` which means the current working directory. If you run the same command in a script the first element will be the path to the directory containing the script.

It's interesting that your output contains `''` twice - it looks like something is injecting an extra `''` into your `sys.path` and that's the cause of the problems.

As for the `import ivy` command... is it the case that if a package is installed using IPython then it's invisible to the regular Python installation and vice versa? If so, you'd have to install Ivy using `python3` (or its linked copy of `pip`) for it to be visible to it. I'm not familiar enough with IPython to know how it handles package installs.

**Comment by dmulholland** [comment]
As a useful diagnostic, if you run:

    cat $(which ivy)

it will print the content of the entry script created by `pip`. The first line will give you the exact location of the Python binary that's being used.

**Comment by boada** [comment]
Just as a small update: I've run into this issue twice now, on two different machines. One machine had a brand new install of Python3.6, one was my daily work machine with all of the stuff I've used over the years. In both cases, renaming `sites.py` to `sites.conf` solves the problem. 

Feel free to close this issue if you want to. I just wanted to bring it to attention.

**Comment by dmulholland** [comment]
Thanks for the update - and sorry for the delay in getting back to you. I was off on holiday.

I've just pushed 0.6.0 which will hopefully resolve this issue. It changes the name of the site configuration file to `config.py` which shouldn't conflict with anything in the standard library.

Thanks for all the feedback, it was really helpful. Please do reopen this issue if for some reason the update doesn't work for you.
