### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by asyncee** [dmulholland/ivy#10]
Hello and thank you for such a great library, two questions — is this project intended for use as documentation builder or can one build blog with it?

If it is possible to build static blog with Ivy, then i should ask if pagination can be implemented?

**Comment by KricketK** [comment]
https://mulholland.xyz/docs/ivy/faq.html#can-i-build-a-blog-using-ivy

Text:
Sure, but you'll have to write some code to do it.

Ivy is actually a stripped-down version of an older static website generator that I tinkered with for years called Malt, which was fully blog-capable. One of the lessons I learned along the way is that it's pretty much impossible to build a simple, elegant, general-purpose static-website-plus-blog engine — it just ends up being a WordPress-style rat's nest of options and switches.

It's actually quite easy to build a blog on top of Ivy by adding a simple plugin to assemble indexes, etc. — at least, it's easy to do it for one specific site. I've certainly thought about building a general-purpose blog plugin, but it inevitably turns into its own mini rat's nest of options and switches all over again.

I don't have any personal use for a blog so I probably never will get around to working on the problem again, but if anyone else wants to try they're welcome to take a look at Malt for inspiration.

**Comment by asyncee** [comment]
Thank you for detailed answer.

**Comment by dmulholland** [comment]
Thanks @KricketK. Sorry about the slow response @asyncee. Ivy is optimised for building simple sites but you could take a look at the indexing and pagination code in [Malt](https://github.com/dmulholland/malt) and consider adapting it for your own use.
