### ISSUE TITLE
Include documentation unclear about where `inc` namespace is available

### ISSUE THREAD

**Issue by rawrgulmuffins** [dmulholland/ivy#12]
# What Happened
According to the Ivy documentation 

> The includes directory, inc, is intended for snippets of content that can be reused on multiple pages throughout the site, e.g. menus or footer links. Source files placed in this folder will be parsed as Markdown or Monk depending on their extension and the resulting HTML made available for inclusion in template files via the inc.<name> attribute. 

Which reads to me that I should be able to use `inc.<name>` in a similar way to c macro's at any point in any node. I figured out that what includes really do is add a object in the jinja template namespace. That's not super clear in the documentaiton

# Documentation Fix

> The includes directory, inc, is intended for snippets of content that can be reused on multiple pages throughout the site, e.g. menus or footer links.  Source files placed in this folder will be parsed as Markdown or Monk depending on their extension and the resulting HTML made available for inclusion in template files via the inc.<name> attribute.
> 
> NOTE: The `inc` namespace is not available in Markdown or Monk files themselves.

# What I was trying to do.

```
 cat about.md
---
title: About
---
inc.menu
[alexlord@AlexLords-MacBook-Pro ~/git/personal/alord_dragonstepsfire.com/site/src] :) ls
about.md	index.mk
[alexlord@AlexLords-MacBook-Pro ~/git/personal/alord_dragonstepsfire.com/site/src] :) ls ../inc/
menu.md		pure.css
```

![screen shot 2018-02-10 at 10 06 27 pm](https://user-images.githubusercontent.com/1521575/36070418-0e1bd9aa-0eaf-11e8-8d09-0e053ee1507f.png)

**Comment by dmulholland** [comment]
Thanks, I've updated the documentation to hopefully be a bit clearer about the distinction. 

This is actually a use case for [shortcodes](http://mulholland.xyz/docs/ivy/extensions.html#shortcodes). If you drop this [plugin file](https://github.com/dmulholland/ivy-plugins/blob/master/ivy_sc_include.py) into your site's `ext` directory it will enable an `[% include %]` shortcode the you can use to include the content of files from the `inc` directory directly into node files.

Just use it with the name of the file you want to include:

    [% include foobar.md %]

**Comment by rawrgulmuffins** [comment]
Ahh, that's a nifty little thing. I saw that section in the documentation but I hadn't wrapped my head around the distinction between nodes and templates. It took me a couple of hours to understand and I've used a lot of Jinja templates. =P

**Comment by rawrgulmuffins** [comment]
@dmulholland This seems fixed to me. Would you like me to close or should you?

**Comment by dmulholland** [comment]
Thanks, I'm glad you like it! It's nice to see people getting use out if it.

I'm going to add a proper section on shortcodes to the documentation when I get time - they're a really easy and powerful way to customise a site. I might add that `[% include %]` shortcode to the skeleton site as a sample plugin to give people an idea of what they're capable of.

Thanks for the feedback, it's been really useful.
