### ISSUE TITLE
subjective CLI description change

### ISSUE THREAD

**Issue by epogrebnyak** [dmulholland/ivy#13]
Given ivy is an elegant program, can we change in command line `[FLAGS]` to `[-vh]` or `[-t | -v]`? 

`[FLAGS]` really screams to me, and feel prepares to an array of modifiers, while there is just two.

**Comment by dmulholland** [comment]
It's an interesting point, the capital letters are a little shouty. I think the simplest solution is just to remove `[FLAGS]` etc. from the usage line - on reflection, they add visual clutter without really helping anyone.

Thanks for pointing it out.
