### ISSUE TITLE
Making a blog

### ISSUE THREAD

**Issue by tyeeman** [dmulholland/ivy#16]
Saw your post in ycombinator about ivy. How would I make a blog with posts on the main page listed? Tags would be nice too.

**Comment by dmulholland** [comment]
It's possible but probably not something I'm going to add support for myself. I wrote a bit about it before in the [FAQ][] explaining my reasoning.

My goal for Ivy is to keep the core as simple as possible so it ages gracefully. It's very flexible so you could certainly create a plugin to add blog-style indexes and tags, but it would require digging into the code. 

[FAQ]: https://darrenmulholland.com/docs/ivy/faq.html#can-i-build-a-blog-using-ivy
