### ISSUE TITLE
GitLab Pages

### ISSUE THREAD

**Issue by dAnjou** [dmulholland/ivy#17]
I've created a so-called _[Gitlab Pages](https://pages.gitlab.io) example_: https://gitlab.com/dAnjou/ivy ([demo](https://danjou.gitlab.io/ivy)).

It's waiting for [review](https://gitlab.com/pages/pages.gitlab.io/issues/71) to be in the official list. Once it's official the links will be: https://gitlab.com/pages/ivy and https://pages.gitlab.io/ivy.

Just FYI 🙂

**Comment by dAnjou** [comment]
Oh, and if you're using Twitter they can also send out a tweet about it mentioning you (I don't use Twitter). Let me know your handle and I'll add it to the review issue.

**Comment by dmulholland** [comment]
Great idea, thanks :) Definitely drop me a link when it goes live. And thanks for the offer but I'm not on Twitter either.
