### ISSUE TITLE
Redirect multiple paths

### ISSUE THREAD

**Issue by gduverger** [dmulholland/ivy#18]
This is not an issue but, for what it's worth, I wrote an extension to allow multiple paths to the same node by using the keyword `redirects` in `./src/foo.md` (e.g., `redirects: bar, foo-bar`) and I figured others might be interested: https://gist.github.com/gduverger/452f00dc195612edd6733ee6cde0d5d3.

At the very least, it was a great way to better understand Ivy. 😄

**Comment by dmulholland** [comment]
Interesting idea. Glad you're finding Ivy useful :)
