### ISSUE TITLE
Photos/pictures ?

### ISSUE THREAD

**Issue by ebreton** [dmulholland/ivy#5]
Hi,

I find ivy very interesting, and I have just started to play with it. 

What would be your recommendation with regards to the file structure when images come into play ? 

Let's say we want a main picture and some galleries for any given post: where would you put those pictures/photos in order to keep the content well structured ?

Cheers,
Manu

PS: I am a python developer, used to install Wordpress for family and friends when it comes to blog

**Comment by dmulholland** [comment]
Hi Manu.

The resources directory `res` is intended for image files and the like - its content gets copied to the output directory when the site is built.

If you have a file called `photo.jpg` in a folder called `images` within `res` then its url in template and node files would be:

    @root/images/photo.jpg

You could implement a WordPress-style 'featured image' mechanic pretty simply just by adding the image name as a attribute to the page header:

    ---
    title: Page Title
    image: photo.jpg
    ---

Then you could check for it in the template file:

    {% if node.image %}
        <img src="@root/images/{{ node.image }}">
    {% endif %}

YAML supports lists so you could implement galleries similarly by having a list of image names in the header and iterating over the list in the template:

    {% for image in node.gallery %}
        <img src="@root/images/{{ image }}">
    {% endfor %}

Hope that helps!

**Comment by ebreton** [comment]
yes, that answers my question :)

thanks a lot !
