### ISSUE TITLE
Last Updated Feature

### ISSUE THREAD

**Issue by jayeshbadwaik** [dmulholland/ivy#7]
Hi,

First, thanks for the website generator, it is extremely useful. 

Is it possible to insert a "last updated" timestamp in the website? 

Cheers

**Comment by dmulholland** [comment]
Hi Jayesh.

If you're using a `.ibis` template like the one in the default theme then timestamps are supported directly by the template language itself. You can add a:

    {{ now|dtformat("format string") }}

tag anywhere you like in a template file. `now` is a datetime object instantiated at the instant the page is created. The format string supports Python's full range of datetime formatting codes specified here:

https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

(You can leave it blank for a default timestamp.)

I haven't tried it but I'm sure Jinja supports something similar.

**Comment by jayeshbadwaik** [comment]
Thanks. This works for me.
