### ISSUE TITLE
Please don't use the unlicense

### ISSUE THREAD

**Issue by mkesper** [dmulholland/ivy#8]
"Unlicense" will create only trouble globally. See e.g. discussion here: https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

**Comment by heyitswither** [comment]
+1

**Comment by ishenyi** [comment]
+1

**Comment by dmulholland** [comment]
It's an interesting point. My favourite alternative would be the MIT license, but I'm not a fan of the requirement to include the copyright notice in "all copies or substantial portions of the Software". It imposes a burden I'd rather avoid and it introduces an element of ambiguity - what exactly constitutes a "substantial portion" of the software? What if somebody just wants to take a function or two from the code? If they do take a function and then adapt it and refactor it as time goes by, when can they stop including my copyright notice? I hate thinking about these issues and I don't want to impose the burden of thinking about them on others.

I've seen some projects dual licensing their code under a public domain declaration like the Unlicense alongside the MIT license, presumably to avoid the issue you've raised. I'd be happy to do that but I'm not sure it makes any sense to simultaneously disavow copyright in one license while claiming it in another.

I'd love to read an authoritative analysis of the issue by an expert in international copyright law.

In the meantime I think the declaration of intent in the Unlicense would be pretty clear to any hypothetical court examining the issue. I'm open to better solutions though - I'd be happy if there was an accepted solution to this problem that meant I didn't have to think about it any more!

**Comment by mkesper** [comment]
Maybe [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) would suit you, then?

> I hate wasting time thinking about these issues and I don't want to impose the burden of thinking about them on others.

As long as the default of Copyright is "All rights reserved" we're compelled to care about it.
Including a copyright notice like the [X.Org license](https://www.x.org/releases/X11R7.7/doc/xorg-docs/License.html#X.Org_Preferred_License) does not seem to be too much of a burden to me, though.
